id: I212810AD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:23:11+00:00'
last_modified: '2022-06-08T08:30:43.890720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22009
  title: སུམ་ཅུ་པའི་སྙིང་པོ་ལེགས་བཤད་ལྗོན་དབང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E1B0:
      image_group_id: I4861
      title: ''
      total_pages: 146
      order: 1
      base_file: E1B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
