id: P009085
initial_creation_type: ocr
source_metadata:
  id: bdr:W22009
  title: སུམ་ཅུ་པའི་སྙིང་པོ་ལེགས་བཤད་ལྗོན་དབང
  author: ''
  volumes:
    13ff1258b9384cfab494ae71f7c3fe53:
      image_group_id: I4861
      title: ''
      volume_number: 1
      total_pages: 146
