id: P009085
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22009
  title: སུམ་ཅུ་པའི་སྙིང་པོ་ལེགས་བཤད་ལྗོན་དབང
  author: ''
  volumes:
    13ff1258b9384cfab494ae71f7c3fe53:
      image_group_id: I4861
      title: ''
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
